# Generated by Django 5.1.2 on 2024-10-15 10:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Permission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('Client', 'Client'), ('Docteur', 'Docteur'), ('Infirmier', 'Infirmier'), ('Admin', 'Admin')], max_length=10)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Utilisateur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_utilisateur', models.CharField(max_length=100)),
                ('mot_de_passe', models.CharField(max_length=255)),
                ('role', models.CharField(choices=[('Client', 'Client'), ('Docteur', 'Docteur'), ('Infirmier', 'Infirmier'), ('Admin', 'Admin')], max_length=10)),
                ('id_personne', models.IntegerField()),
                ('id_permission', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='administrateur.permission')),
            ],
        ),
    ]
